[package]
    name = "attestation"
    version = "0.1.0"

[dependencies]
    elrond-wasm = "0.5.1"
    elrond-wasm-node = "0.5.1"
    elrond-wasm-derive = "0.5.1"

[lib]
    path = "src/lib.rs"

[[bin]]
    name = "attestation"
    path = "src/lib.rs"